### ISSUE TITLE
Pipelined background closure compiler

### ISSUE THREAD

**Issue by denji** [roman01la/webpack-closure-compiler#1]
- [**closure-gun**](https://github.com/closure-gun/closure-gun) – gets around the long startup time of [Google Closure Compiler](https://developers.google.com/closure/compiler/) using [Nailgun](https://github.com/closure-gun/nailgun), which runs a single java process in the background and keeps all of the classes loaded.
  
  Nailgun is a client, protocol, and server for running Java programs from the command line without incurring the JVM startup overhead.
- [**drip**](https://github.com/ninjudd/drip) – is a launcher for the Java Virtual Machine that provides much faster
  startup times than the `java` command. The `drip` script is intended to be a
  drop-in replacement for the `java` command, only faster.
  - https://github.com/ninjudd/drip/blob/master/README.md

**Comment by roman01la** [comment]
Do you want to integrate it into webpack plugin? I think that should be a separate installation. So if someone wants it, he can install. I'll just add those link into readme. Thanks.
