### ISSUE TITLE
Clousure Compiler doesn't like `__WEBPACK_IMPORTED_MODULE_3_helpers__`

### ISSUE THREAD

**Issue by mohsen1** [roman01la/webpack-closure-compiler#19]
I'm using Webpack 2.1 beta 27 with TypeScript that generates ES6. When I use this plugin, I get errors like this:

```
stdin:7597: ERROR - The class in an extends clause must be a qualified name.
class APIClientError extends __WEBPACK_IMPORTED_MODULE_3_helpers__["e" /* CustomError */] {
                             ^
```

Not sure how to tell CC to allow those class names?  I couldn't find anything in CC documents.

**Comment by mohsen1** [comment]
First I thought it's the hanging `__` but changing [this line](https://github.com/webpack/webpack/blob/master/lib/dependencies/HarmonyModulesHelpers.js#L14) to remove starting `__` didn't help. 

Issue is `__WEBPACK_IMPORTED_MODULE_3_helpers__["e" /* CustomError */]` is not a valid JavaScript class identifier for Closure Compiler but it's perfectly valid JS.

**Comment by roman01la** [comment]
I have no idea. According to this issue in CC repo, they do not support these kind of names https://github.com/google/closure-compiler/issues/1876#issuecomment-231138616

**Comment by mohsen1** [comment]
I made [another issue](https://github.com/google/closure-compiler/issues/2182). `a['foo']` is **not** dynamic. It's static.

**Comment by roman01la** [comment]
Nice. I'll close this issue then.
