### ISSUE TITLE
Externs?

### ISSUE THREAD

**Issue by romanoff** [roman01la/webpack-closure-compiler#2]
Are there any plans to have an ability to use externs (maybe through options)?

**Comment by roman01la** [comment]
@romanoff Hi. Sorry, I'm not really using it anymore. You can add what you want and send a PR.

**Comment by HiroAgustin** [comment]
@roman01la what would be the way to configure the externs? https://github.com/facebook/react/issues/9417#issuecomment-315432639

**Comment by roman01la** [comment]
@HiroAgustin Try to add them as `externs` option

```
{
  externs: ["path/to/extern.js"]
}

**Comment by HiroAgustin** [comment]
Thanks.
