### ISSUE TITLE
Question about plugin

### ISSUE THREAD

**Issue by xtuc** [roman01la/webpack-closure-compiler#28]
Sorry, I never used the Closure compiler.

I wanted to know why this still require `babel-loader`? Couldn't the Closure compile just be a loader in Webpack where JavaScript goes through?

**Comment by roman01la** [comment]
Hi. You don't need babel-loader, Closure Compiler is pretty good at transpilation (see https://kangax.github.io/compat-table/es6/#closure). Also it is not a loader plugin, but a replacement for UglifyJS.

**Comment by xtuc** [comment]
I was thinking if this plugins couldn't directly be a loader in Webpack (since it doesn't need Babel, depending on the JavaScript features used).

Thanks for your answer.

**Comment by thaoms** [comment]
So, what do you guys use as js loader then? I guess js stuff still needs to be resolved?
