### ISSUE TITLE
Latest perf numbers with webpack 2/3 ? Way to reproduce ?

### ISSUE THREAD

**Issue by fabm22** [roman01la/webpack-closure-compiler#35]
Looking at the very interesting [part](https://github.com/roman01la/webpack-closure-compiler#why-use-closure-compiler-instead-of-uglifyjs) of the README with comparison of different sizes of produced js with different corresponding tools, I was wondering if we could have updated numbers with notably (for me) latest versions of webpack (2 &+), and possibly TypeScript compiler ?

Also is there some documentation of how to reproduce the exact same setup so anyone could potentially update the numbers ?

Thanks a lot

**Comment by roman01la** [comment]
The results was taken from this benchmark, feel free to update it https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016
