### ISSUE TITLE
Source Map uses unpermitted temp write

### ISSUE THREAD

**Issue by kriffe** [roman01la/webpack-closure-compiler#42]
Unsure if this is due to some other package interfering or if its just that it occurs on my Windows 10 setup.

Whenever I enable the create_source_map flag i get the following error.

Seems connected to local write permissions https://github.com/roman01la/webpack-closure-compiler/blob/master/index.js#L76

No global npm packages used here

```
c:\Users\kriffe\Documents\GitHub\myapp\node_modules\temp\node_modules\rimraf\rimraf.js:137
      throw er
      ^

Error: EPERM: operation not permitted, unlink 'C:\Users\kriffe\AppData\Local\Temp\ccwp-dump-118113-25284-fjnwc5.lnizg'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at rimrafSync (c:\Users\kriffe\Documents\GitHub\myapp\node_modules\temp\node_modules\rimraf\rimraf.js:211:13)
    at cleanupFilesSync (c:\Users\kriffe\Documents\GitHub\myapp\node_modules\temp\lib\temp.js:88:5)
    at process.cleanupSync (c:\Users\kriffe\Documents\GitHub\myapp\node_modules\temp\lib\temp.js:195:19)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
```

**Comment by roman01la** [comment]
Hi. Happy to merge a PR to fix this!

**Comment by bansawbanchee** [comment]
@kriffe 
What version of node are using? 
Do you have any anti-virus software running?

**Comment by kriffe** [comment]
@bansawbanchee : v8.9.4

**Comment by bansawbanchee** [comment]
Do you have any anti-virus software running?

If you have Windows Defender turned on disable it and try again.

Alot of times anti-virus real time protection stops software from writing files.

**Comment by kriffe** [comment]
@bansawbanchee Error not due to anti-virus. 

@roman01la : Created PR with solution. Please add correct patch number and test https://github.com/roman01la/webpack-closure-compiler/pull/43

**Comment by Aqours** [comment]
Same issue.

system: windows 10
node: 10.0.0
webpack-closure-compiler: 2.1.6
google-clousre-compiler: 20170521.0.0
