### ISSUE TITLE
Passing multiple externs

### ISSUE THREAD

**Issue by ccoffey** [roman01la/webpack-closure-compiler#8]
Can you please add an example of how to pass multiple externs? The following does not appear to be working.

``` javascript
new ClosureCompilerPlugin({
  compiler: {
    language_in: 'ECMASCRIPT5',
    language_out: 'ECMASCRIPT5',
    compilation_level: 'ADVANCED',
    externs: [
      'node_modules/google-closure-compiler/contrib/externs/underscore-1.5.2.js',
      'node_modules/google-closure-compiler/contrib/externs/jquery-1.9.js'
    ]
  },
  concurrency: 3,
})
```

**Comment by roman01la** [comment]
Hi. There's no support for externs. Feel free to submit a PR. It should be fairly simple to implement.

**Comment by roman01la** [comment]
I'm reopening this issue. Looks like externs are supported and I can see Closure Compiler does use them. But I'm not experienced with externs. Can you please help me to understand how to check that externs doesn't work?

**Comment by roman01la** [comment]
I'm closing this issue. Please reopen if you encounter this again.
