### ISSUE TITLE
Building react.js with Advanced compilation gives error.

### ISSUE THREAD

**Issue by tonis2** [roman01la/webpack-closure-compiler#9]
Bundling works good but, browser gives error.
Uncaught TypeError: (0 , f.default) is not a function 
from closure-compiler Faq i found 

> If you are using ADVANCED optimizations, you may also want to disable the type-based optimizations with --use_types_for_optimization false. Incorrect type optimizations can cause the compiler to make invalid assumptions

but where should i add this .--use_types_for_optimization false ?

**Comment by roman01la** [comment]
Hi, you should path this option into _compiler_ configuration.

``` js
        new ClosureCompilerPlugin({
          compiler: {
            language_in: 'ECMASCRIPT6',
            language_out: 'ECMASCRIPT5',
            compilation_level: 'ADVANCED',
            use_types_for_optimization: false
          },
          concurrency: 3,
        })
```

Hope that helped.
